name: scheduler

on:
  schedule:
    # Runs at AM 7:10(GMT+09:00)
    - cron: '10 22 * * *'

jobs:
  batch:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run main.py
        run: python main.py --sort

      - name: Git commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -a -m '[Bot] Update files' || echo 'Nothing to commit'

      - name: GitHub push
        # git push https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        run: |
          git remote -v
          git push origin HEAD:${{ github.ref }}
